# See https://fly.io/docs/reference/configuration/ for information about how to use this file.


app = "lunchautomate-api"
primary_region = "ams"
console_command = "/code/manage.py shell"

[deploy]
  release_command = "python manage.py migrate"

[env]
  PORT = "8000"

[processes]
  web = "gunicorn --bind :8000 --workers 2 lunchautomate.wsgi"
  cron = "supercronic /code/crontab"

[[services]]
  http_checks = []
  internal_port = 8000
  processes = ["web"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

[[statics]]
  guest_path = "/code/static"
  url_prefix = "/static/"
